const videoMetadata = [
["fishing dreamcast.mov","fishing pole","fish","Sega Bass Fishing","Sega Fishing Pole"],
["guitar hero regular.mov","guitar","music","Guitar Hero","Guitar Hero guitar"],
["contra bongos.mov","drum","fight","Contra","Donkey Kong bongos"],
["mario bowling ball.mov","bowling ball","run","Mario","Wii bowling ball"],
["mario steering wheel.mov","steering wheel","run","Mario","Playstation steering wheel"],
["tetris steering wheel.mov","steering wheel","puzzle","Tetris","Playstation steering wheel"],
["car videogame with real car as controller.mov","steering wheel","drive","Forza","actual Lamborghini"],
["real car with ps2 controller.mov","default","drive","real driving","ps2 controller"],
["call of duty with steering wheel.mov","steering wheel","fight","Call of Duty","Playstation steering wheel"],
["dark souls steering wheel.mov","steering wheel","fight","Dark Souls","Wii steering wheel"],
["fishing pole dark souls.mov","fishing pole","fight","Dark Souls","Sega Fishing Pole"],
["call of duty rock band .mov","drum","fight","Call of Duty","Rock Band Drum"],
["thrasher skate and destroy ps1.mov","default","skate","Thrasher Skate and Destroy","Ps1 Controller"],
["metro cross NES skateboard.mov","default","skate","Metro Cross NES","Nintendo Gamepad"],
["skitching sega genesis 1994.mov","default","skate","Skitching Sega Genesis","Sega Gamepad"],
["tony hawk ride actual skateboard.mov","skateboard","skate","real skating","Tony Hawk skateboard controller"],
["cuphead ddr.mov","dance pad","fight","Cuphead","Dance Dance Revolution Pad"],
["resident evil dance pad.mov","dance pad","fight","Resident Evil","Dance Dance Revolution Pad"],
["tekken on dance pad.mov","dance pad","fight","Tekken","Dance Dance Revolution Pad"],
["james bond golden eye dance pad.mov","dance pad","fight","James Bond ","Dance Dance Revolution Pad"],
["super mario ddr pad.mov","dance pad","run","Super Mario","Dance Dance Revolution Pad"],
["smash bros ddr pad.mov","dance pad","fight","Super Smash Bros.","Dance Dance Revolution Pad"],
["street fighter with ddr pad.mov","dance pad","fight","Street Fighter","Dance Dance Revolution Pad"],
["guitar hero modern warfare.mov","guitar","fight","Call of Duty","Guitar Hero guitar"],
["pro evolution soccer ps1.mov","default","soccer","Pro Evolution Soccer","Ps1 Controller"],
["final soccer vr.mov","vr headset","soccer","Final Soccer","Virtual Reality Headset"],
["fifa soccer 17 xbox one.mov","default","soccer","Fifa Soccer","Xbox Controller"],
["wii fit u soccer.mov","balance pad","soccer","Wii Fit Soccer","Wii Balance Pad"],
["n64 internaitonal superstar soccer.mov","default","soccer","Superstar Soccer","N64 gamepad"],
["virtua stiker 2 dreamcast .mov","default","soccer","Virtua Striker","Dreamcast gamepad"],
["kick off amiga 1989.mov","default","soccer","Kick Off Amiga","Joystick and Buttons"],
["pele's soccer atari 2600 1981.mov","default","soccer","Pele Soccer","Atari Gamepad"],
["Atari Soccer (1980).mov","default","soccer","Atari Soccer","Atari Gamepad"],
["Donkey Konga.mov","drum","music","Donkey Konga","Donkey Kong bongos"],
["dk bongo for switch.mov","drum","fight","Knight Terrors","Donkey Kong bongos"],
["NES super glove ball.mov","glove","tennis","Super Glove Ball","Power Glove"],
["NES power glove controls drone.mov","glove","fly","actual drone flight","Power Glove"],
["pong.mov","default","tennis","pong","gamepad"],
["wii bowling ball perfect for Boxing.mov","bowling ball","fight","Wii Boxing","Wii bowling ball"],
["soul caliber with fishing controller.mov","fishing pole","fight","Soul Caliber","Sega Fishing Pole"],
["sega activator.mov","activator","fight","Greatest Heavyweights of the Ring","Sega Activator"],
["playchoice 10 tennis.mov","default","tennis","Playchoice Tennis","Joystick and Buttons"],
["ambush alley.mov","light gun","fight","Ambush Alley","Action Max Lightgun"],
["ddr.mov","dance pad","dance","Dance Dance Revolution","Dance Dance Revolution Pad"],
["Virtual Boy Tennis.mov","default","tennis","Virtual Boy Tennis","gamepad"],
["bigbuckhunter.mov","light gun","hunt","Big Buck Hunter","Light Gun"],
["htcvive tennis.mov","default","tennis","Tennis","Virtual Reality Headset"],
["wiitennis.mov","default","tennis","Wii Tennis","Wii Remote"],
["tennisfortwo.mov","default","tennis","Tennis for Two","First Game Controller"],
["super hang on with activator.mov","activator","drive","Super Hang-On","Sega Activator"],
["sonic with activator.mov","activator","run","Sonic","Sega Activator"],
["ddr balance pad.mov","balance pad","dance","Dance Dance Revolution","Wii Balance Pad"],
["wii fit plus skateboarding balance pad.mov","balance pad","skate","Wii Fit Skateboarding","Wii Balance Pad"],
["dark souls balance pad.mov","balance pad","fight","Dark Souls","Wii Balance Pad"],
["simpsons hitrun bongos.mov","drum","drive","Simpsons Hit n Run","Donkey Kong bongos"]
];
